### ISSUE TITLE
Add multiple dataviews: Visual not loading

### ISSUE THREAD

**Issue by rwedoff** [Microsoft/PowerBI-visuals-tools#11]
When trying to add multiple dataviews into capabilities
 the visual doesn't load.  Only getting the loading circle in the top left corner.  

[capabilites.txt](https://github.com/Microsoft/PowerBI-visuals-tools/files/403909/capabilites.txt)

**Comment by itslenny** [comment]
This is a limitation of Power BI. Your visual's data mapping cannot request data that would result in more than one query. Generally, you should only use 1 data mapping at a time. You can use conditions to switch between them, but only 1 data mapping should be valid under any set of conditions otherwise the query will fail and result in the loading circle that you're seeing.

**Comment by Zahma** [comment]
@itslenny Hello, how can we set conditions inside the capabilities.json to switch between different dataviews ?

**Comment by ignatvilesov** [comment]
Power BI Custom Visuals API doesn't support more than a data view.
In other words, there's no ability to switch to another `dataView`.
