### ISSUE TITLE
applyJsonFilter - Merge FilterAction

### ISSUE THREAD

**Issue by jay-pillai** [Microsoft/PowerBI-visuals-tools#150]
Its not clear what the FilterAction does. It doesnt seem the Merge seems to work by keeping previously added column filters.

@EugeneElkin @AviSander - any help appreciated.

**Comment by whitneyland** [comment]
It's not clear because they refuse to keep the api documentation up to date including what's new, what's deprecated, etc.  The repos are the same way, they're not properly marked deprecated when they need to be, so much stale information.

I've mentioned before to a couple ms devs on pbi github repos, who gave a response indicating quality of developer platform and experience is not really a priority to them, even though I tried to explain it helps Power BI as much as it helps us.

Next time I'm on campus I'm going to try and find a way to steal a few seconds with James Phillips.  He's a busy guy, but I believe he would understand more clearly, that keeping github and APIs sharp and fresh is a key factor to building momentum for Power BI as a platform.

There's really no excuse.  Even if they're busy, they could also ask for help from an MVP, or one of us here, with small but important tasks like this.  I'm sure there are people in the community who wouldn't mind pitching in a bit to keep things nice around here, I know I'd be willing to help if that's what it's going to take.

**Comment by AviSander** [comment]
please take a look at https://github.com/Microsoft/powerbi-visuals-sampleslicer/blob/master/doc/UsingAdvancedFilterAPI.md for some more info.

we're working on updating this documentation.

as for filterAction:
merge is the default action: apply the filter.
remove is to effectively clear the current filter.
