### ISSUE TITLE
"conditions" of dataViewMappings works strangely

### ISSUE THREAD

**Issue by KoBe321** [microsoft/PowerBI-visuals-tools#343]
Drag and dropping fields is not always working when there are at least 2 conditions with the setting min: 1, max: 1.

1. open the report
2. remove the Category field from the Category Data bucket using the x
3. remove the Quantity field also
4. now you can't drag and drop the Category back to the Category Data

[Capabilities bug.zip](https://github.com/microsoft/PowerBI-visuals-tools/files/5616357/Capabilities.bug.zip)

**Comment by vision-anywhere** [comment]
If min is set for a category, that category must have data before any other category can be used. In practice, I've found that setting min on multiple fields means the visual is impossible to use - the user can't fill in two fields simultaneously. 
It sounds like it's working as intended. Can you share your `capabilities.json` file?

**Comment by KoBe321** [comment]
I forgot to mention that I'm using this Visual and I just extended the capabilities.json.
https://github.com/microsoft/PowerBI-visuals-sampleBarChart
![image](https://user-images.githubusercontent.com/8909363/100623249-3077e300-3322-11eb-905e-a4be0cd291a0.png)

**Comment by vision-anywhere** [comment]
Yeah, in practice you can really only have one `min` condition in total. If you have one, that category needs to be filled before any other. If you have two categories with a min, they both need to be filled, but each one prevents you from putting a field in the other. It essentially shoots itself in the foot. I would choose one or the other.

If you really want to enforce minimums for more than one category, I would suggest checking the presence of datafields in the visual's script and, if the minimum isn't met, printing a warning instead of any visual display. You can see this in practice in the rhtml funnel-plot [tutorial](https://github.com/microsoft/PowerBI-visuals/blob/master/RVisualTutorial/TutorialFunnelPlot/chapter3_RCustomVisual/funnelRvisual_v03/script.r)

**Comment by KoBe321** [comment]
I think we might not be talking about the same things. :)
To clarify it, I've made a short clip:
https://drive.google.com/file/d/1uXlgfZYfVCDowgLvoopW4igCfAycOJCV/view

I think it's not obvious that I had to fill back "Measure Data" first and then only I'm able to fill "Category Data".

**Comment by vision-anywhere** [comment]
No, I understood - it's best practice to use the script itself to check the fields requirements rather than `dataviewmappings`. `max` plays nice, `min` does not. I can't answer why, but the pbiviz devs seem content with the way it works as per this [post](https://community.powerbi.com/t5/Custom-Visuals-Development/DataViewMapping-Conditions-Not-Working-as-Expected/td-p/726187). 

Even if `min` worked as the docs indicate (I agree with you), checking inputs in your script is better from a usability standpoint. `min`'s behavior is frustrating to an end user, as you have found, since there isn't an avenue of informing the user of the visual's input conditions explicitly with `dataviewmappings`. Printing an error using the visual script based on inputs met and unmet allows informing the user what they have wrong, and allows exerting more control over the input conditions required for the visual to display. The best way to move forward is to ditch `min` (it doesn't hurt to keep `max` ) and provide minimum input conditions in the visual's script.
