### ISSUE TITLE
Tutorial - Developing Your First PowerBI Visual - Building a Static Visual

### ISSUE THREAD

**Issue by magtuto** [Microsoft/PowerBI-visuals-tools#35]
I am currently mowing my way through the tutorial.  

I believed that I followed the instructions on how to  Setting Up Environment.  Therefore I have started on the section on building a bar chart.

On the section that relates to Building a Static Visual I have just cut and pasted the code re Setting up ViewModel section.  So with just this code I tried to package the file (pbiviz package) and I received this error.

error TYPESCRIPT /visualPlugin.ts : <8,56> Property 'visual' does not exist on type 'typeof extensibility'

I should be able to just try to package this section and it should work right?

Secondly, is the visual playground still operational?

**Comment by raananzvi** [comment]
Hi,

Please provide some more information (the code that fails) so we can take a look. The packaging should work after each step, as long as you don't have issues.
You can see a link to a full commit at each of those steps (search for the word commit on the page) so you can have a reference to what should be done.
If you still encounter some issues, please reply.

Regarding the visual playground, this feature is deprecated, we are moving away from the old way to create custom visuals, to the new CLI tools which exposes a versioned APIs which will make sure your custom visual will always get a consist set of APIs from Power BI and your code won't break due to internal changes in Power BI code.
You should learn how to develop using the new interfaces, and share your required and missing features from the API so we will go ahead and support them.
You can find a roadmap for the new developer tools here: https://github.com/Microsoft/PowerBI-visuals/blob/master/Roadmap/README.md

**Comment by mehulumistry** [comment]
I am stuck with the same error:

"error  TYPESCRIPT  /visualPlugin.ts : (8,146) Property 'Visual' does not exist on type 'typeof project_name18E995418150443A8CFACE6D6A95ABA8'."
Below attached my project folder.

[pii.zip](https://github.com/Microsoft/PowerBI-visuals-tools/files/1884864/pii.zip)

**Comment by uve** [comment]
@mehulumistry, to compile the project, please change **visualClassName** to **PieChart**. And use d3 v3.5
